### ISSUE TITLE
Build API for existing Splice UI 

### ISSUE THREAD

**Issue by tspurway** [oyiptong/splice#112]
Splice's UI currently allows for upload, preview and building of distributions.  This featureset will eventually become the 'approval workflow' section of splice 2, but needs to be ported to our new stack. 

This bug is to determine which API calls are required to support existing functionality, and to implement them.

**Comment by rlr** [comment]
I discussed with @tspurway and we'll be doing this off of the master branch since it doesn't require anything from splice 2.

**Comment by tspurway** [comment]
The existing API may be sufficient to support a React front-end.  Please close if this is the case.

**Comment by ncloudioj** [comment]
Yes, I think the current API is already for this. Close it.
