### ISSUE TITLE
Port existing Splice UI to new stack

### ISSUE THREAD

**Issue by tspurway** [oyiptong/splice#113]
This feature is to refactor our existing AngularJS UI in Splice to use our new stack - feature-for-feature.

**Comment by ncloudioj** [comment]
According to the new biz requirement, we're looking to add country as one of targets for content suggested tiles. E.g. running content tiles for locale "en-US" in "US". That will significantly decrease the size of tile set (we used to run content tiles for all "en-US" FF users), thus, the slow tile loading as well as the massive memory usage will no longer be bugging us in the near future.

Depends on where do we stand in the development, I think that we can put the UI enhancement on hold, and focus on the "Approval Workflow" and the related UI now. What do you guys think? @tspurway @rlr

**Comment by rlr** [comment]
I am game either way. I'll assume we will continue down this path unless there is something else that takes priority?

**Comment by tspurway** [comment]
I think we continue on.  There are a number of advantages to moving our codebase to a single UI library and make some incremental improvements.  We have some time now, let's continue on.

**Comment by ncloudioj** [comment]
Sounds good. Let's wrap it up then.

**Comment by rlr** [comment]
Filed pull request #153

**Comment by ncloudioj** [comment]
awesome. i am on it.
