### ISSUE TITLE
sp2 API Requirements for initial front end pages

### ISSUE THREAD

**Issue by tkiethanom** [oyiptong/splice#117]
Depends on #121 

Basic API for accessing Accounts, Campaigns, Ad Groups and Tiles. Including sorting, paging and basic filtering. 

Related Parent-child data may also need to be pulled in when getting a Model by Id. 

https://docs.google.com/spreadsheets/d/167My3CyemsL_ARLrriHR4QwPOpOapypclMJ5ad4rp6Q/edit#gid=0

**Comment by tspurway** [comment]
Transcribing from the spreadsheet.

Url | Header | Description | GET Params | POST/PUT Body formatted as JSON
--- | ------ | ----------- | ---------- | -------------------------------
/accounts | GET | list all accounts | sortBy, sortDirection, page, query* | 
/accounts | POST | creates new account |  | name, email, phone, etc.
/accounts/:accountId | GET | get account by accountId |  | 
/accounts/:accountId | PUT | update account by accountId |  | name, email, phone, etc.
 |  |  |  | 
/campaigns | GET | list all campaigns or list by accountId | accountId, sortBy, sortDirection, page, query* | 
/campaigns | POST | creates new campaign |  | accountId, name, country, city, region, etc.
/campaigns/:campaignId | GET | get campaign by campaignId |  | 
/campaigns/:campaignId | PUT | update campaign by campaignId |  | accountId, name, country, city, region, etc.
 |  |  |  | 
/adgroups | GET | list all adgroups or list by campaignId | campaignId, sortBy, sortDirection, page, query* | 
/adgroups | POST | creates new adgroup |  | campaignId, name, locale, etc.
/adgroups/:adgroupId | GET | get adgroup by adgroupId |  | 
/adgroups/:adgroupId | PUT | update adgroup by adgroupId |  | campaignId, name, locale, etc.
 |  |  |  | 
/tiles | GET | list all tiles or list by adgroupId | adgroupId, sortBy, sortDirection, page, query* | 
/tiles | POST | creates new tile |  | adgroupId, title, target_url, image_url, etc.
/tiles/:tileId | GET | get tile by tileId |  | 
/tiles/:tileId | PUT | update tile by tileId |  | adgroupId, title, target_url, image_url, etc.

**Comment by tspurway** [comment]
We are closing this bug, as we have delivered basic PUT, POST and GET endpoints for Accounts, Campaigns, Adgroups and Tiles.

We are opening new bugs for the remaining functionality:

- sort attribute, sort direction, pagination (#128)
- filtering by campaign activity and status and endpoints for *all campaigns*, *all tiles* and *all adgroups* (#129)

**Comment by tkiethanom** [comment]
For sake of consistency the campaign endpoint should be plural _/campaign**s**/:accountId_
