### ISSUE TITLE
splice-2.0 Browser prevents cross-domain access to API

### ISSUE THREAD

**Issue by tkiethanom** [oyiptong/splice#118]
We are currently having cross-domain (CORS) issues when trying to access the Splice API that is living on our staging server. Browsers prevent javascript from accessing other domains unless specifically enabled by the endpoint. We would like to request the following header be added to the response for development purposes: 

`Access-Control-Allow-Origin: *`

This could be enabled by an environment variable or an argument when starting the server.

**Comment by ncloudioj** [comment]
Confirmed. Will enable it soon.

**Comment by ncloudioj** [comment]
Hey @tkiethanom, just want to confirm that are you using the `splice2` branch in your development env? We're looking to migrate all the APIs to the `sp2` branch now, if this feature(CORS) is essential for you, we could do a quick hotfix here before the migration.

**Comment by tkiethanom** [comment]
Correct our API is currently running on `splice-2.0` branch. We've found a work around for the time being using a browser plugin. So as long as its fixed in `sp2` I think that will be okay.

**Comment by ncloudioj** [comment]
@tkiethanom Thanks for confirming it. So we'll stop adding new things to `splice-2.0`, this one will be added to `sp2` shortly.

**Comment by tkiethanom** [comment]
I hit some more cross domain issues when trying to do a POST. 

These headers are also necessary:

`Access-Control-Allow-Headers: Content-Type`
`Access-Control-Allow-Methods: POST, GET, PUT`

**Comment by ncloudioj** [comment]
Reopen this issue as currently, the default error response from Flask-Restful didn't handle CORS properly.
