### ISSUE TITLE
splice-2.0 API CSRF token missing or incorrect.

### ISSUE THREAD

**Issue by tkiethanom** [oyiptong/splice#119]
Receiving this response when POSTing to `/api/accounts`

```
{
  "message": "CSRF token missing or incorrect."
}
```

**Comment by ncloudioj** [comment]
@tkiethanom are you running Splice server locally?

For development env, you can turn off CSRF by creating a `localconfig.py` at the top level of project, and paste the following snippet,
```Python
from splice.default_settings import DefaultConfig

class LocalConfig(DefaultConfig):
    AWS = None
    CSRF = False

```

Then put this line to your .bashrc or .zshrc
```bash
# for splice testing
export SPLICE_SETTINGS=localconfig.LocalConfig

```

**Comment by rlr** [comment]
Long term, we probably want to rething this CSRF thing though. I've never seen an API require that. They usually require auth for modifying data though, and we don't have that yet.

**Comment by ncloudioj** [comment]
Agreed, I think this is just a global configuration for the current Splice. For the API stuff, it's unnecessary.

**Comment by tkiethanom** [comment]
Actually the API is running on a CentOS server. I tried adding that line to the /etc/bashrc and restarting the API but it didn't seem to change anything.

**Comment by tkiethanom** [comment]
False alarm its working now. I had to start a new screen.
