### ISSUE TITLE
Model Changes for Campaign DB

### ISSUE THREAD

**Issue by tspurway** [oyiptong/splice#121]
Current Model | New Model | Reason
------------- | --------- | ------
campaigns.locale | adgroups.locale | current campaigns (like booking.com) are run across multiple locales
campaigns.paused | campaigns.paused, tiles.paused, adgroups.paused | parent's paused status overrides childrens'

Deprecated fields: adgroups.[locale, start_date, end_date, start_date_dt, end_date_dt, channel_id], tiles.locale

**Comment by tspurway** [comment]
This issue is also tracking getting the existing model working in sp2

**Comment by ncloudioj** [comment]
The summary of the model change:
 
* New fields: adgroups.[paused, type("directory" | "suggested")], tiles.[paused, status("approved" | "disapproved" | "unapproved")]
* Deprecated fields: adgroups.[start_date, end_date, start_date_dt, end_state_dt, channel_id],
campaings.locale, tile.locale

@tspurway make sense?

**Comment by tspurway** [comment]
this is OK, go ahead
