### ISSUE TITLE
Bulk Upload API Endpoint

### ISSUE THREAD

**Issue by tkiethanom** [oyiptong/splice#133]
API should receive file and process it to generate Ad Groups and Tiles for the specified Campaign ID. 

/api/campaigns/:campaignId/bulkupload

**Comment by tspurway** [comment]
So we have a couple of things to decide about the input format.  Here's a start:

        {
            "categories": [category1, category2], 
            "created_at": "Sat, 15 Aug 2015 15:20:33 -0000", 
            "explanation": "An entertainment site suggestion", 
            "frequency_cap_daily": 1, 
            "frequency_cap_total": 1, 
            "locale": "en-US", 
            "name": "a name", 
            "paused": false, 
            "type": "a type",
            "tiles":[
                {
                    "bg_color": "", 
                    "created_at": "Sat, 15 Aug 2015 15:20:53 -0000", 
                    "enhanced_image_uri": "base64_encoded_image", 
                    "image_uri": "base64_encoded_image", 
                    "paused": false, 
                    "status": "unapproved", 
                    "target_url": "https://www.yahoo.com/health/boxing-moves-125521155502.html?soc_trk=mz&mz_cat=health_fitness", 
                    "title": "Yahoo", 
                    "title_bg_color": null, 
                    "type": "affiliate"
                }
            ]
        }, 


The one issue is obviously what to do about images.  I think our current ingest process already has encoded images.  @ncloudioj what do you think?

**Comment by ncloudioj** [comment]
Will be looking into the image processing next. The current workflow won't be working any more. A couple of things we need to consider,

* Integrate the "qconvert" into the Splice to convert raw creatives (png,jpeg,svg) into b64-encoded strings.
* In the response json payload, "image_uri" and "enhanced_image_uri" would be URLs that point to the creatives on S3. We're currently storing image hashes in the database. We might have to store both of them in the database.
* Caching, we don't want to store duplicate images. It's already implemented in Splice, need to make it to work for the new workflow.

**Comment by tkiethanom** [comment]
Any updates on this?

**Comment by ncloudioj** [comment]
Hey @tkiethanom . I am currently looking into this one. Messing around different approaches here. Will keep you posted!

**Comment by ncloudioj** [comment]
@tkiethanom This feature has been implemented. For more details, please see PR #170
