### ISSUE TITLE
Reporting API 

### ISSUE THREAD

**Issue by tspurway** [oyiptong/splice#138]
Because we have distinct `stats` and `campaign` databases, any query that requires Account, Campaign or Adgroup level rollups will require data from both databases.  This can be done either as two explicit queries for each API request, or optimized with a variety of caching schemes.  For the first release of this, we will not implement a cache.

The following URL patterns are the API:

```/accounts/stats/<period>/<start_date>
/accounts/<id>/stats/<period>/<start_date>
/campaigns/<id>/stats/<period>/<start_date>
/adgroups/<id>/stats/<period>/<start_date>
/tiles/<id>/stats/<period>/<start_date>
```

Note that the `/accounts/stats` will return results rolled up for each account.

For the URLs with an `<id>`, the returning JSON will have a single row for each `<period>` of stats for the identified object.  The `<period>` is either `weekly`, `daily`, or `monthly`, and the `<start_date>` is encoded `YYYY-MM-DD`.  For example, the URL:

`/campaigns/15/stats/daily/2015-09-01`

will return one row rolled up for each day of stats for `campaign_id=15` since September 1st.

**Return Vaues**

The JSON return document will contain an array of maps, with each map containing the following fields:
- clicks
- impressions
- pins
- blocks
- click-through rate
- block rate
- `<period>` date
- `<name>` or `<title>`
- `<id>`

**Query Parameters**

By default, you will get one row for *all* countries, locales and channels for the requested object.  In order to filter along these dimensions, you can specify the `countries`, `locales` and `channels` query parameters, each of which takes a comma separated list of values to be filtered for.

By default the sort order will be by `<period>`, but can be changed using the `sort` attribute.  Order is by default ascending, but can be changed using the `sort_order` parameter.

Initially there will be no pagination supported.

Initially there will be *not* be the ability to pivot on additional columns like `locale`, `country` or `channel`.

**Comment by k88hudson** [comment]
This was resolved with 35a2abc
