### ISSUE TITLE
API returns "No adgroups found"

### ISSUE THREAD

**Issue by tkiethanom** [oyiptong/splice#139]
When hitting /api/adgroups?campaign_id=123 the api responds with a "404 No adgroups found" instead of returning an empty set. This also happens for /api/tiles but not for /api/campaigns.

**Comment by ncloudioj** [comment]
Confirmed. Will fix it to return an empty set.
Note that it'll return 404 if you're looking for a single item(tile, adgroup, campaign). i.e. /api/adgroups/1234
