### ISSUE TITLE
Additional APIs needed for Campaigns

### ISSUE THREAD

**Issue by tkiethanom** [oyiptong/splice#144]
I need to be able to grab all Channels and Countries to fill dropdowns for creating and updating Campaigns.

**Comment by ncloudioj** [comment]
Yup, will add those ones shortly.

**Comment by tspurway** [comment]
You will also need a list of locales.  Let's pay attention to the ordering of the country and locales - they should be ordered by popularity (US, CA, UK, ...) (en-US, es-US, fr-FR, etc.) not alphabetically

**Comment by tkiethanom** [comment]
In the current API, locale is a field of Ad Groups.

**Comment by tspurway** [comment]
@tkiethanom - good point - we won't need locales
