### ISSUE TITLE
Field Validation for Accounts/Campaigns (client side)

### ISSUE THREAD

**Issue by tspurway** [oyiptong/splice#146]
Field | Type | Checks | Required
------ | ------- | ---------- | -------------
Account.name | String | len(s) > 1 | Y
Account.contact_name | String | n/a | N
Account.contact_email | String | n/a | N
Account.contact_phone | String | n/a | N
Campaign.name | String | len(s) > 1 | Y
Campaign.start_date | Date  | YYYY-MM-DD  | Y
Campaign.end_date | Date  | YYYY-MM-DD  | Y
Campaign.channel | Channel | values from /channels API | Y
Campaign.countries | List of Countries | values from /countries API | Y

**Comment by tkiethanom** [comment]
The Date format should match https://github.com/oyiptong/splice/issues/142 right?

Campaigns also have a `countries` field which is an array.

**Comment by tspurway** [comment]
@tkiethanom, because of the fact that Firefox only fetches tilesets every day, we do not need full date + time resolution on start and end dates for data entry.  We only need a date picker, and that date should be displayed in iso8601 subset YYYY-MM-DD
