### ISSUE TITLE
tiles.image_uri and tiles.enhanced_image_uri contain HASHes not URIs

### ISSUE THREAD

**Issue by tspurway** [oyiptong/splice#159]
We need to replace the data in these columns with the actual URIs.  These URIs can be fetched from S3 by searching for the object with the corresponding hash as the prefix.

This would require one S3 lookup for each tile, then a SQL `update` statement for each found URI.  This should be OK, as there are only a few thousand tiles.

This functionality should be added to the scripts/index_walker.py data migration script.

**Comment by tspurway** [comment]
@ncloudioj - is this one done as well?

**Comment by ncloudioj** [comment]
yes, it's fixed by the data migration script.
