### ISSUE TITLE
Add auto reporting feature to zenko

### ISSUE THREAD

**Issue by k88hudson** [oyiptong/splice#163]
This will need some thinking in terms of specific requirements.

**Comment by mzhilyaev** [comment]
Could you outline a general need for the feature - what is "auto reporting" suppose to solve.

**Comment by k88hudson** [comment]
@mzhilyaev I agree, I am guessing we will also want to leave this for a future release. I will coordinate with Annelise and Matt on this

**Comment by k88hudson** [comment]
After discussing this, @ashonnard and I have decided it makes sense for this to be in the integration with splice. We're also going to look at saved queries and history instead of just auto reporting
