### ISSUE TITLE
Sort by date

### ISSUE THREAD

**Issue by k88hudson** [oyiptong/splice#164]
"This way when pulling monthly reporting we can auto group by date"

**Comment by mzhilyaev** [comment]
Kate, could you elaborate on this, because the monthly report query for a tile already does ORDER BY date ASC.  Do you mean some other page?

**Comment by k88hudson** [comment]
To be honest I'm not sure. I copied these from a list of requests in a google doc by Annelise and Matt, let's get them to clarify once they're on github. Maybe put this one on hold 'til then.

**Comment by k88hudson** [comment]
Resolved
