### ISSUE TITLE
Add filters to exporting functionality

### ISSUE THREAD

**Issue by k88hudson** [oyiptong/splice#165]
e.g. export report by category

**Comment by mzhilyaev** [comment]
I assume this is "download for excel" button that needs to provide export by category.
The logic of zenko (as I understood it), suggests that a user needs to involve various controls (like country menu or date selection widget) to place a report on the screen and then download.
Am I wrong, or it's some specific report that you meant?

**Comment by k88hudson** [comment]
We added some filters and will be improving them in https://github.com/oyiptong/splice/issues/225
