### ISSUE TITLE
Building JS assets bundle in Fabric

### ISSUE THREAD

**Issue by tspurway** [oyiptong/splice#173]
Our deployment process includes a packaging step using `fab package` which ends up running the Fabric file `./fabfile.py`.  

During the package phase, we need to build JS bundles for both `./ui` and `./front_end`.

@k88hudson and @rlr: what is a good strategy for integrating WebPack with Fabric?

**Comment by rlr** [comment]
We would have fabric do something like:

```
$ cd ui
$ npm install
$ npm run-script bundle
```

And then it can move the bundle files around if needed or we can configure webpack to put them in the right place from the getgo.

**Comment by k88hudson** [comment]
If you wanted to, you could add `npm run bundle` as a `postinstall` script as well.

Also @rlr you don't need to call `./node_modules/webpack/bin/webpack.js` in your script, npm adds webpack's bin directory to the path automatically -- you can just call `webpack` in your script

**Comment by k88hudson** [comment]
i agree that calling npm from fabric is the best approach :+1:

**Comment by rlr** [comment]
There is now a `build_ui` command in the fabric file. 56d40fa802c5a939fb0ce99bb9f628b284b3849f
