### ISSUE TITLE
Landing page for Splice 2

### ISSUE THREAD

**Issue by tspurway** [oyiptong/splice#174]
We currently have two distinct UIs in Splice: the distribution UI (`./ui`) and the Campaign Mgmt UI (`./front_end`).  We need a deployment strategy so that users can easily navigate between these UIs.

This could be a landing page, or a navigation element added to all the existing pages.  Ideas?

**Comment by rlr** [comment]
Right now these are two separate apps, but I am guessing longterm we'll only have one app. We would merge them, tossing whatever we don't need anymore from the old UI.

That said. For now... I guess we would need to have them live at two separate paths? Something like this maybe:

* `/` has the landing page
* `/old/` has the app in `./ui`
* `/sp2/` has the app in `./frontend`

Thoughts?

**Comment by tkiethanom** [comment]
If you want to direct users to a single url a landing page would be useful. It's also probably likely users will want to jump back and forth between them. So both.

**Comment by rlr** [comment]
If we expect a lot of back and forth, then maybe I should go ahead and move existing UI into the sp2 app?

**Comment by rlr** [comment]
landed be7fb967c9e1dfa060d3ae8657283cb9fd5ac17d
