### ISSUE TITLE
Add API for Uploading individual creative

### ISSUE THREAD

**Issue by ncloudioj** [oyiptong/splice#192]
This API allows user to upload individual creative to S3, it handles the image processing, caching, and returns the URL on S3 for that creative to the client.

The API endpoint: "api/tiles/creative/upload"

**Comment by ncloudioj** [comment]
@tkiethanom When user uploads the creative manually (as composed to the bulk upload), the UI needs to hit this API to complete the image uploading. Please let me know if you have questions.

**Comment by tkiethanom** [comment]
How does the image get attached to the Tile? Doesn't this need a TileId to reference?

**Comment by ncloudioj** [comment]
Nope, it only takes care of the image processing, uploading to S3 if it's not cached. Then it returns the URL for the fields (image_uri) and (enhanced_image_uri). That means the image uploading should happen before you summit the new tile to the server. Note that the image_uri and enhanced_image_uri might be mutatable in the future, but for now the user needs to provide those two when creating a new tile.

**Comment by ncloudioj** [comment]
Hey @tkiethanom. So I have merged this feature into sp2 branch.
The endpoint is "api/tiles/creative/upload", it takes a "creative" field as the submitted form argument. If succeeds, it'll return a url, which points to the uploaded image. Otherwise, an error message will be sent back to the client. Similar to other APIs, they are both in JSON. For instance,
```JSON
{
  "result": "https://bucket.s3.aws.com/images/1234.123.png"
}
```
or,
```JSON
{
  "message": "Error: failed to upload creative, unsupported image format."
}
```

**Comment by rlr** [comment]
API and UI has landed.
