### ISSUE TITLE
In the Campaign Database, incorrect DDL for `created_at` column

### ISSUE THREAD

**Issue by tspurway** [oyiptong/splice#195]
The column should never be set by any client code, it should always be set using a default timestamp from the server.  This means we should also disable access to this column from all APIs

**Comment by ncloudioj** [comment]
Will stop taking the `created_at` on the server side. The client side could stop using this field.

**Comment by rlr** [comment]
Stealing from @ncloudioj to work on.

**Comment by rlr** [comment]
Landed:
db92a197fdc2a3bc096099751b2a693b3afcc1ab
