### ISSUE TITLE
Use A Different Bucket for Development

### ISSUE THREAD

**Issue by ncloudioj** [oyiptong/splice#199]
We should use a different bucket on S3 for development. The bucket has already been created, only need to point to it in the settings file.

**Comment by oyiptong** [comment]
Do you mean for a development environment?

**Comment by oyiptong** [comment]
who will have access to this environment?

I set one up for @tkiethanom: moz-tiles-dev

**Comment by ncloudioj** [comment]
Yes. I assume everyone should have access to that bucket.
