### ISSUE TITLE
The Explanation Field is Only For The Directory Tiles

### ISSUE THREAD

**Issue by ncloudioj** [oyiptong/splice#206]
Similar to the `categories` and `frequency caps`, the `explanation` field is only for `suggested tiles`. Therefore, it should not be shown or editable for the `directory tiles`.

**Comment by rlr** [comment]
Fixed 33aedb8c0bb7f3b756d163f0147b947e6fe19198

**Comment by rlr** [comment]
oops. wrong issue

**Comment by rlr** [comment]
NVM. this was addressed in the PR too. FIXED for realz
