### ISSUE TITLE
When adding adgroups to an android (channel_id=3) campaign, they get the desktop channel_id assigned.

### ISSUE THREAD

**Issue by rlr** [oyiptong/splice#237]
We have `channel_id` in two places for backwards compatibility. When creating adgroups, they should inherit the `channel_id` of the campaign they are created in. Right now it doesn't seem to be happening.

STR:
* Create a campaign for Android channel
* Create an adgroup for it
* Check the adgroup's channel_id in the database

**Comment by rlr** [comment]
It appears once you create the adgroup, you can't go edit the channel anymore. You can't delete the adgroup either. So you are stuck with the mistake forever :sob:

**Comment by rlr** [comment]
Anyway... My vote would be to:

* Remove channel selection from the "Add Adgroup form"
* Set the channel on the server side when creating adgroups based on the campaign's channel

The way it is now we can end up with conflicting data that is impossible to fix via the UI.

**Comment by tkiethanom** [comment]
I've always thought the intention was to eventually remove one of them. 

I'll remove it from the AdGroup Form now.

**Comment by rlr** [comment]
@tkiethanom Can you pass the channel_id of the campaign when calling the API? Otherwise, we'll need an API side change too. Thanks

**Comment by tkiethanom** [comment]
Yea I can do that for now, but we should fix this on the server side like you mentioned above.
