### ISSUE TITLE
Removing country from input should be easier

### ISSUE THREAD

**Issue by oyiptong** [oyiptong/splice#240]
Remove an entry from the campaign/country input field is annoying.

When hitting backspace, one would expect the whole entry to disappear, same as hitting the 'X' button.
Each screenshot (save for the first one) is after hitting backspace with focus on the input:

<img width="2672" alt="screen shot 2015-11-18 at 1 46 33 pm" src="https://cloud.githubusercontent.com/assets/9365/11250551/eb8384a6-8dfa-11e5-883e-6efcc3309192.png">
<img width="2672" alt="screen shot 2015-11-18 at 1 46 39 pm" src="https://cloud.githubusercontent.com/assets/9365/11250556/eec7a642-8dfa-11e5-962d-0e8620d95f74.png">
<img width="2672" alt="screen shot 2015-11-18 at 1 46 45 pm" src="https://cloud.githubusercontent.com/assets/9365/11250558/f18e173a-8dfa-11e5-8501-08c30be0e8ea.png">
<img width="2672" alt="screen shot 2015-11-18 at 1 46 50 pm" src="https://cloud.githubusercontent.com/assets/9365/11250560/f384be54-8dfa-11e5-9352-6e7e1c19a267.png">

**Comment by tkiethanom** [comment]
This is how the plugin works but I'll look into it.

**Comment by tkiethanom** [comment]
This has been addressed by switching to react-select plugin.
