### ISSUE TITLE
Campaign Cancel doesn't work

### ISSUE THREAD

**Issue by oyiptong** [oyiptong/splice#241]
Hitting cancel in the campaign menu doesn't do anything

**Comment by oyiptong** [comment]
There's a console warning:

```
Warning: You cannot PUSH the same path using hash history
```

Probably a pushState bug

**Comment by k88hudson** [comment]
@tkiethanom this is resolved right?

**Comment by tkiethanom** [comment]
@k88hudson I could never reproduce it, and I don't have access to the dev environment. Ricky mentioned the dev environment hasn't been updated.

**Comment by rlr** [comment]
Just tested the cancel button on dev for both the campaign add and edit screens. They both worked. Closing.
