### ISSUE TITLE
I cannot save a new account 

### ISSUE THREAD

**Issue by HerminaC** [oyiptong/splice#260]
http://splice_tiles.dev.mozaws.net/ -> Campaign app -> Create new - I can insert all info but I cannot save the new account created (made different attempts, attached 2 tests).

![account doesn t save](https://cloud.githubusercontent.com/assets/7406447/11396574/587d735e-936a-11e5-8688-633c5846aa0f.png)
![account doesn t save 2nd test](https://cloud.githubusercontent.com/assets/7406447/11396580/5d37bb70-936a-11e5-9b7b-15bdfbfc4794.png)

**Comment by k88hudson** [comment]
@tkiethanom can you take a look at this?

**Comment by tkiethanom** [comment]
@rlr or @k88hudson is this only happening in the dev environment?

**Comment by k88hudson** [comment]
@tkiethanom Yes, I think this might be related to an issue with the server crashing actually -- we're just looking into it right now

**Comment by k88hudson** [comment]
@tkiethanom ok, server issue seems to be resolved

**Comment by k88hudson** [comment]
@HerminaC I think this is now resolved. Can you confirm?

**Comment by HerminaC** [comment]
Hi Kate,
Yes, I confirm it's now resolved. Thanks!
