### ISSUE TITLE
Avoid Running Out of Database Connections

### ISSUE THREAD

**Issue by ncloudioj** [oyiptong/splice#264]
Make sure closing the database session when the query finishes. We've done that for write sessions, but haven't done that for those read sessions yet.

```shell
_wrap_pool_connect
    return fn()
  File "/opt/splice/lib/python2.7/site-packages/sqlalchemy/pool.py", line 376, in connect
    return _ConnectionFairy._checkout(self)
  File "/opt/splice/lib/python2.7/site-packages/sqlalchemy/pool.py", line 713, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/splice/lib/python2.7/site-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/opt/splice/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1053, in _do_get
    (self.size(), self.overflow(), self._timeout))
TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 10
2015-11-25 18:05:01 [26070] [DEBUG] POST /api/distributions
```

**Comment by ncloudioj** [comment]
After going through the doc of SQLAlchemy, we have two configuration items to tweak if we frequently run into this issue. In particular, as more and more users are using the dev/prod server now.

* SQLALCHEMY_POOL_SIZE: (5 by default), this is the size for database connection pool. We can definitely increase it.
* SQLALCHEMY_MAX_OVERFLOW: (10 by default), this is to control the number of connections that can be created after the pool reached its maximum size. All those extra connections will be discarded once the pool has connections available again.

**Comment by tspurway** [comment]
can we close this one @ncloudioj ?

**Comment by ncloudioj** [comment]
yup, we've already fixed it.
