### ISSUE TITLE
UI Gets Clunky When A Campaign Runs in A Lot of Countries

### ISSUE THREAD

**Issue by ncloudioj** [oyiptong/splice#285]
Came across the following situation when a campaign has a long list of target countries. Needed to scroll a long way down to see the other details.

Perhaps we can elapse the country list in this case, and only show a quick preview by default. For instance, "United States, Canada, Germany, ...". Users can expand the list if they want to view the whole list.

<img width="591" alt="screen shot 2015-12-03 at 2 22 21 pm" src="https://cloud.githubusercontent.com/assets/1455254/11571287/951d4496-99c9-11e5-803a-b0d2973f2449.png">

**Comment by tkiethanom** [comment]
Ok will do. 

I imagine this causes a problem in the campaign list view as well right?

**Comment by ncloudioj** [comment]
That's correct! Thanks @tkiethanom
