### ISSUE TITLE
"fab build_ui" failed during splice deployment

### ISSUE THREAD

**Issue by ncloudioj** [oyiptong/splice#290]
@rlr and @tkiethanom  Can anyone take a look at this issue please? https://bugzilla.mozilla.org/show_bug.cgi?id=1230670 

It also failed to build locally. Looks like it has to do with the new dependent libraries.

Thanks.

**Comment by tkiethanom** [comment]
Ok I'm on it.

**Comment by tkiethanom** [comment]
Make sure the history package is the correct version. In `package.json` the package is set to 1.13.1. You should be able to just run `npm install history` on the server.

**Comment by tkiethanom** [comment]
Oh sorry, the problem is in `ui` not `front_end`.

**Comment by rlr** [comment]
I'll take a look.

**Comment by tkiethanom** [comment]
The package versions just need to be locked

**Comment by rlr** [comment]
Submitted PR #291

**Comment by rlr** [comment]
This should be fixed now bf3ef59e9d83ed64babd60698712617e3e7a1229
